language: java
cache:
  directories:
    - ${HOME}/.m2
    - ${TRAVIS_BUILD_DIR}/dependencies
sudo: required
before_install:
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${PWD}
  - echo "====== DEPENDENCIES - Start ======"
  - sudo apt-get install tree
  - export DEP_DIR=${TRAVIS_BUILD_DIR}/dependencies
  - tree ${DEP_DIR}
  - echo "====== MAVEN - Start ======"
  - export MVN_VERSION=3.5.0
  - export M2_HOME=${DEP_DIR}/maven/apache-maven-${MVN_VERSION}
  - export PATH=${M2_HOME}/bin:${PATH}
  - test -d ${M2_HOME} || (wget https://archive.apache.org/dist/maven/maven-3/${MVN_VERSION}/binaries/apache-maven-${MVN_VERSION}-bin.zip && unzip -qq apache-maven-${MVN_VERSION}-bin.zip -d ${DEP_DIR}/maven)
  - mvn --version
  - mvn help:evaluate -Dexpression=settings.localRepository | grep -E '^([/a-zA-Z0-9_. \-]+)$'
  - echo "====== MAVEN - End ======"
  - tree ${DEP_DIR}
  - echo "====== DEPENDENCIES - End ======"
jdk:
  - oraclejdk8
